# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
      with:
        node-version: '20'
    - name: Set up Swift
      uses: actions/setup-swift@latest-version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
